"""
Deep analysis of L629174_RFI_dataset.pkl before any model touches it.

WHY RUN THIS FIRST
------------------
The HERA dataset shipped with 31 test images that were byte-identical copies of
training images (22% of its test set). That was only caught because it was
checked. This script runs the same checks -- and more -- on the LOFAR file before
any result gets computed from it.

WHAT "REAL" MEANS HERE (important caveat, confirmed from the source paper)
--------------------------------------------------------------------------
The LOFAR *measurements* are genuine telescope observations -- L629174 is a real
LOFAR observation ID. But the RFI *masks* are NOT human-drawn. Mesarcik et al.
state the labels are "weak-labels in the form of RFI flags (generated by classical
RFI flagging methods)", and RFI-NLN uses "the python wrapping for AOFlagger".

So the answer key is another algorithm's opinion, not ground truth. A model
scored against it is being measured on how well it imitates AOFlagger -- exactly
the same limitation Akeret et al. had with SumThreshold. The paper offers a small
expert-labelled subset separately; this file is not it.

MEMORY
------
The pickle is 3.78 GB on disk and expands further in RAM. Run this in WSL, not in
a small container. Peak usage is roughly 8-10 GB.

USAGE
    source ~/torch-env/bin/activate
    cd "/mnt/c/Users/RONAK SINGH/Documents/Coding/Minor Project"
    python3 lofar_analysis/analyse_lofar.py
"""
import os, sys, gc, json, pickle, hashlib, argparse
import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.normpath(os.path.join(_HERE, ".."))


def describe(o, name="root", depth=0, out=None):
    pad = "  " * depth
    if isinstance(o, np.ndarray):
        line = f"{pad}{name}: ndarray shape={o.shape} dtype={o.dtype}"
        print(line, flush=True)
        if out is not None:
            out.append(dict(name=name, shape=list(o.shape), dtype=str(o.dtype)))
        return
    if isinstance(o, dict):
        print(f"{pad}{name}: dict keys={list(o.keys())[:20]}", flush=True)
        for k in list(o.keys())[:12]:
            describe(o[k], str(k), depth + 1, out)
        return
    if isinstance(o, (list, tuple)):
        print(f"{pad}{name}: {type(o).__name__} len={len(o)}", flush=True)
        for i, v in enumerate(o[:8]):
            describe(v, f"[{i}]", depth + 1, out)
        return
    print(f"{pad}{name}: {type(o).__name__} -> {str(o)[:100]}", flush=True)


def find_pairs(obj):
    """Locate (image, mask) array pairs: float arrays and bool arrays of matching leading dim."""
    arrays = []

    def walk(o, path="root"):
        if isinstance(o, np.ndarray):
            arrays.append((path, o))
        elif isinstance(o, dict):
            for k, v in o.items():
                walk(v, f"{path}.{k}")
        elif isinstance(o, (list, tuple)):
            for i, v in enumerate(o):
                walk(v, f"{path}[{i}]")
    walk(obj)
    imgs = [(p, a) for p, a in arrays if a.dtype.kind in "fiu" and a.dtype != np.bool_ and a.ndim >= 3]
    msks = [(p, a) for p, a in arrays if a.dtype == np.bool_ or (a.dtype.kind in "iu" and a.max() <= 1)]
    return arrays, imgs, msks


def img_stats(a):
    """Per-image statistics, computed one image at a time to bound memory."""
    n = a.shape[0]
    mx, mn, p01, p99, med = [], [], [], [], []
    nan = inf = 0
    for i in range(n):
        x = np.asarray(a[i], dtype=np.float32).ravel()
        nan += int(np.isnan(x).sum()); inf += int(np.isinf(x).sum())
        x = x[np.isfinite(x)]
        if x.size == 0:
            continue
        mx.append(float(x.max())); mn.append(float(x.min()))
        p01.append(float(np.percentile(x, 1))); p99.append(float(np.percentile(x, 99)))
        med.append(float(np.median(x)))
    return dict(n=n, max=np.array(mx), min=np.array(mn),
                p01=np.array(p01), p99=np.array(p99), med=np.array(med),
                n_nan=nan, n_inf=inf)


def mask_stats(m):
    n = m.shape[0]
    fr = np.empty(n)
    tot = pos = 0
    for i in range(n):
        b = np.asarray(m[i]).astype(bool)
        fr[i] = b.mean(); tot += b.size; pos += int(b.sum())
    return fr, tot, pos


def dupes(a, label):
    h = [hashlib.sha256(np.ascontiguousarray(a[i]).tobytes()).hexdigest() for i in range(a.shape[0])]
    u = set(h)
    print(f"  {label}: {len(u)} unique / {a.shape[0]}  ({a.shape[0]-len(u)} duplicates)", flush=True)
    return h, u


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pkl", default=os.path.join(_ROOT, "L629174_RFI_dataset.pkl"))
    p.add_argument("--out", default=os.path.join(_HERE, "lofar_report.json"))
    a = p.parse_args()

    print("=" * 78)
    print(" LOFAR L629174 -- deep dataset analysis")
    print("=" * 78)
    print(f"  file: {a.pkl}")
    print(f"  size: {os.path.getsize(a.pkl)/1e9:.2f} GB")
    print("  loading (this needs several GB of RAM) ...", flush=True)
    with open(a.pkl, "rb") as f:
        obj = pickle.load(f)
    print("  loaded.\n")

    print("--- STRUCTURE ---")
    struct = []
    describe(obj, out=struct)

    arrays, imgs, msks = find_pairs(obj)
    print(f"\n  {len(arrays)} arrays total | {len(imgs)} look like images | {len(msks)} look like masks")

    report = dict(file=os.path.basename(a.pkl), size_bytes=os.path.getsize(a.pkl),
                  structure=struct, splits=[])

    # pair them up by leading dimension, in order
    used = set()
    for ip, ia in imgs:
        partner = None
        for mp, ma in msks:
            if mp in used or mp == ip:
                continue
            if ma.shape[0] == ia.shape[0] and ma.shape[1:3] == ia.shape[1:3]:
                partner = (mp, ma); used.add(mp); break
        if partner is None:
            continue
        mp, ma = partner
        print("\n" + "=" * 78)
        print(f" SPLIT: images={ip} {ia.shape} {ia.dtype}  |  masks={mp} {ma.shape} {ma.dtype}")
        print("=" * 78, flush=True)

        print("\n--- RFI CLASS BALANCE ---", flush=True)
        fr, tot, pos = mask_stats(ma)
        print(f"  total pixels      : {tot:,}")
        print(f"  RFI pixels        : {pos:,}")
        print(f"  RFI fraction      : {100*pos/tot:.4f}%")
        print(f"  per-image RFI %   : min {100*fr.min():.3f}  median {100*np.median(fr):.3f}  "
              f"mean {100*fr.mean():.3f}  max {100*fr.max():.3f}")
        print(f"  images with 0% RFI: {int((fr==0).sum())} / {len(fr)}")
        print(f"  images >50% RFI   : {int((fr>0.5).sum())} / {len(fr)}")

        print("\n--- PIXEL VALUE DISTRIBUTION ---", flush=True)
        st = img_stats(ia)
        print(f"  NaN pixels        : {st['n_nan']:,}    Inf pixels: {st['n_inf']:,}")
        print(f"  global min / max  : {st['min'].min():.4g} / {st['max'].max():.4g}")
        print(f"  per-image max     : min {st['max'].min():.4g}  median {np.median(st['max']):.4g}  "
              f"max {st['max'].max():.4g}")
        ratio = st['max'].max() / max(st['max'].min(), 1e-12)
        print(f"  per-image max SWING: {ratio:.1f}x   <-- 8.2x is what broke tf_unet on our synthetic data")
        print(f"  per-image median  : min {st['med'].min():.4g}  median {np.median(st['med']):.4g}  "
              f"max {st['med'].max():.4g}")
        print(f"  1st percentile    : mean {st['p01'].mean():.4g}")
        print(f"  99th percentile   : mean {st['p99'].mean():.4g}")
        dyn = np.median(st['max']) / max(np.median(st['med']), 1e-12)
        print(f"  median max/median : {dyn:.1f}x   (>100x means log scaling is essential)")

        print("\n--- DUPLICATE / LEAKAGE CHECK ---", flush=True)
        hi, ui = dupes(ia, "images")
        hm, um = dupes(ma, "masks")
        # same image, different mask?
        by = {}
        for k in range(ia.shape[0]):
            by.setdefault(hi[k], set()).add(hm[k])
        contra = sum(1 for v in by.values() if len(v) > 1)
        print(f"  images appearing with MORE THAN ONE mask: {contra}  (contradictory labels)")

        report["splits"].append(dict(
            images=ip, masks=mp, shape=list(ia.shape), dtype=str(ia.dtype),
            n_images=int(ia.shape[0]), total_px=int(tot), rfi_px=int(pos),
            rfi_fraction=float(pos/tot),
            per_image_rfi=dict(min=float(fr.min()), median=float(np.median(fr)),
                               mean=float(fr.mean()), max=float(fr.max()),
                               n_zero=int((fr==0).sum()), n_over_half=int((fr>0.5).sum())),
            values=dict(global_min=float(st['min'].min()), global_max=float(st['max'].max()),
                        per_image_max_min=float(st['max'].min()),
                        per_image_max_median=float(np.median(st['max'])),
                        per_image_max_max=float(st['max'].max()),
                        per_image_max_swing=float(ratio),
                        median_of_medians=float(np.median(st['med'])),
                        p01_mean=float(st['p01'].mean()), p99_mean=float(st['p99'].mean()),
                        dynamic_range=float(dyn), n_nan=int(st['n_nan']), n_inf=int(st['n_inf'])),
            duplicates=dict(unique_images=len(ui), unique_masks=len(um),
                            dup_images=int(ia.shape[0]-len(ui)),
                            contradictory_label_images=int(contra))))
        del st, fr, hi, hm, by
        gc.collect()

    # cross-split overlap if there is more than one split
    if len(report["splits"]) > 1:
        print("\n" + "=" * 78)
        print(" CROSS-SPLIT OVERLAP")
        print("=" * 78)
        hs = []
        for ip, ia in imgs:
            hs.append((ip, {hashlib.sha256(np.ascontiguousarray(ia[i]).tobytes()).hexdigest()
                            for i in range(ia.shape[0])}))
        for i in range(len(hs)):
            for j in range(i+1, len(hs)):
                ov = hs[i][1] & hs[j][1]
                print(f"  {hs[i][0]} ∩ {hs[j][0]} : {len(ov)} shared images   <-- must be 0")
                report.setdefault("cross_split", []).append(
                    dict(a=hs[i][0], b=hs[j][0], overlap=len(ov)))

    json.dump(report, open(a.out, "w"), indent=2)
    print(f"\nSaved: {a.out}")


if __name__ == "__main__":
    main()
